android:
  config:
    "dynatrace {
      configurations {
        defaultConfig {
          autoStart{
            applicationId 'bfcc9a94-6d5e-4af2-b031-4380107bd4da'
            beaconUrl 'https://bf03065cwi.bf.dynatrace.com/mbeacon'
          }
          userOptIn true
          agentBehavior.startupLoadBalancing true
        }
      }
    }"

ios:
  config:
    "<key>DTXApplicationID</key>
    <string>bfcc9a94-6d5e-4af2-b031-4380107bd4da</string>
    <key>DTXBeaconURL</key>
    <string>https://bf03065cwi.bf.dynatrace.com/mbeacon</string>
    <key>DTXUserOptIn</key>
    <true/>
    <key>DTXStartupLoadBalancing</key>
    <true/>"
